/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#154212",
        "primary-container": "#2d5a27",
        "primary-fixed": "#bcf0ae",
        "primary-fixed-dim": "#a1d494",
        "on-primary": "#ffffff",
        "on-primary-container": "#9dd090",
        "on-primary-fixed": "#002201",
        "on-primary-fixed-variant": "#23501e",
        "inverse-primary": "#a1d494",
        "secondary": "#ac3509",
        "secondary-container": "#fe6f42",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59f",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#631800",
        "on-secondary-fixed": "#3a0a00",
        "on-secondary-fixed-variant": "#852300",
        "tertiary": "#3a3938",
        "tertiary-container": "#51504f",
        "tertiary-fixed": "#e5e2e0",
        "tertiary-fixed-dim": "#c8c6c4",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c5c2c1",
        "on-tertiary-fixed": "#1b1c1b",
        "on-tertiary-fixed-variant": "#474745",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-tint": "#3b6934",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#42493e",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#72796e",
        "outline-variant": "#c2c9bb",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "1.75rem",
        "4xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "20px",
        "container-padding-desktop": "64px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "24px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
